# Generated by Django 4.1.1 on 2022-09-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seamstress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('total', models.IntegerField(verbose_name='Количество товаров')),
            ],
            options={
                'verbose_name': 'Швея',
                'verbose_name_plural': 'Швеи',
            },
        ),
    ]
