# Generated by Django 4.1.1 on 2022-09-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_sewingmachines_seamstress_sewing_machines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sewingmachines',
            options={'verbose_name': 'Швейная машина', 'verbose_name_plural': 'Швейные машины'},
        ),
    ]
